{{- $release_name := .Release.Name }}
{{- range $service := .Values.mongodbService }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  #namespace: free5gc
spec:
  clusterIP: None
  ports:
    {{- range $port := $service.ports}}
    - port: {{ $port.port }}
      #targetPort: http
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    app: {{ $service.selector }}
{{- end }}